desc: Avoid misleading array limit error message
tests:
  - py: r.table_create('2930')
    ot: ({'created':1})
  - py: r.table('2930').insert([{'id':i,'mod':i%5,'foo':5} for i in range(1,1000)]).pluck('first_error', 'inserted')
    ot: ({'inserted':999})
  - py: r.table('2930').coerce_to('array')
    runopts:
      array_limit: 500
    ot: err("RqlRuntimeError", "Array over size limit `500`.", [0])
  - py: r.table('2930').group('mod').coerce_to('array')
    runopts:
      array_limit: 500
    ot: err("RqlRuntimeError", "Grouped data over size limit `500`.  Try putting a reduction (like `.reduce` or `.count`) on the end.", [0])
  - py: r.table('2930').group('foo').coerce_to('array')
    runopts:
      array_limit: 500
    ot: err("RqlRuntimeError", "Grouped data over size limit `500`.  Try putting a reduction (like `.reduce` or `.count`) on the end.", [0])
  - py: r.table_drop('2930')
    ot: ({'dropped':1})
